# Generated by Django 4.2.2 on 2023-11-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='products',
            field=models.ManyToManyField(blank=True, to='items.product'),
        ),
    ]
