# Generated by Django 4.2.2 on 2023-11-21 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cuser_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
