# Generated by Django 4.2.2 on 2023-11-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_cuser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='products',
        ),
    ]
