# Generated by Django 4.2.2 on 2023-11-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_product_user'),
        ('accounts', '0006_remove_cuser_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='user_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.product'),
        ),
    ]
