# Generated by Django 4.2.2 on 2023-12-24 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='media',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='message',
        ),
        migrations.AddField(
            model_name='conversation',
            name='body',
            field=models.TextField(default='message'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='msg_receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='msg_receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='msg_sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='msg_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
